#Specify version
version: '3.9'
#Declare the services
services:
  #Define the service
  docker-react-dev:
    container_name: docker-react-dev
  #Declare build file & context to use
    build:
      context: .
      dockerfile: Dockerfile.dev
  #Mount project directory & node modules directory
    volumes:
    - .:/app
    - /app/node_modules
    #Map the ports
    ports:
      - "3001:3000"
  test:
    container_name: docker-react-test
    #Building based on above image (project name+container name)
    image: docker-react-mac_docker-react-dev
    volumes:
    - '.:/app'
    - '/app/node_modules'
    command: ["npm", "run", "test"]