#Specify base image
FROM node:lts-alpine

#Set up working directory
WORKDIR /app

#Install starting dependencies
COPY package.json/ ./
RUN npm install
RUN npm install react-scripts@4.0.3
#Copy in necessary files
COPY ./ ./

#Default command
CMD ["npm", "start"]