name: Docker Prod Image CI
env:
  DATE_STAMP: $(date +%s)
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Env Variable
      run: echo "date-stamp=${{ env.DATE_STAMP }}" >> $GITHUB_ENV
    - name: Build Prod Docker Image
      run: docker build . --file Dockerfile --tag megancindric/docker-react-mac:latest
    - name: Tag Image With Datestamp
      run: docker image tag megancindric/docker-react-mac:latest megancindric/docker-react-mac:${{ env.date-stamp }}
    - name: Docker Account Login
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Push New Image to DockerHub
      run: docker push megancindric/docker-react-mac:${{ env.date-stamp }}